# Copied from cmdstanr github path.R
#' Get Default Path for methylCIPHER Data
#'
#' This function determines the default directory path where methylCIPHER data,
#' required for SystemsAge and PCClocks, should be stored.
#'
#' @return The default path to the methylCIPHER data directory.
#' @export
get_methylCIPHER_default_path <- function() {
  home <- Sys.getenv("HOME")
  if (.Platform$OS.type == "windows") {
    userprofile <- Sys.getenv("USERPROFILE")
    h_drivepath <- file.path(Sys.getenv("HOMEDRIVE"), Sys.getenv("HOMEPATH"))
    win_home <- ifelse(userprofile == "", h_drivepath, userprofile)
    if (win_home != "") {
      home <- win_home
    }
  }
  return(paste0(home, "/", "methylCIPHER"))
}

#' Set Custom Path for methylCIPHER Data
#'
#' This function allows the user to set a custom directory path for storing
#' methylCIPHER data, which is required for SystemsAge and PCClocks. The specified
#' path is stored in R's options under "methylCIPHER.path".
#'
#' @param path A string specifying the custom path to the methylCIPHER data directory.
#'
#' @return None
#' @export
#'
#' @examples
#' get_methylCIPHER_path() # Default Path
#' set_methylCIPHER_path(".") # Change to "."
#' get_methylCIPHER_path() # New Path
set_methylCIPHER_path <- function(path) {
  options(methylCIPHER.path = path)
}

#' Get Path for methylCIPHER Data
#'
#' This function retrieves the path to the methylCIPHER data directory, which is
#' required for SystemsAge and PCClocks. It first checks if a custom path has been
#' set using [set_methylCIPHER_path()] or [options()]. If no custom path is found, it returns
#' the default path obtained from [get_methylCIPHER_default_path()].
#'
#' @return The path to the methylCIPHER data directory.
#' @export
#'
#' @examples
#' get_methylCIPHER_path() # Default Path
#' set_methylCIPHER_path(".") # Change to "."
#' get_methylCIPHER_path() # New Path
get_methylCIPHER_path <- function() {
  path <- getOption("methylCIPHER.path")
  if (is.null(path)) {
    return(get_methylCIPHER_default_path())
  }
  return(path)
}

#' Dependency Factory
#'
#' Some functions like [calcPCClocks()] and [calcSystemsAge()] requires large external
#' data to be downloaded and loaded into R. The best way to increase the speed
#' of this process is to use qs2 storage format. This function factory generate
#' functions to load in these data based on a template.
#'
#' @param object_name name of object ie SystemsAge_data
#' @param object_hash hash of object generated in data-raw
#'
#' @keywords internal
load_data_function <- function(object_name, object_hash) {
  function(path = NULL) {
    # input validation
    checkmate::assert_character(path, len = 1, null.ok = TRUE)
    file_path <- if (!is.null(path)) {
      path
    } else {
      file.path(get_methylCIPHER_path(), paste0(force(object_name), ".qs2"))
    }
    # read file with qs2
    tryCatch(
      {
        obj <- qs2::qs_read(file_path, validate_checksum = TRUE)
      },
      error = function(e) {
        stop(
          sprintf(
            "Failed to read '%s.qs2'. Did you download '%s.qs2' and passed the path or loaded object to this function?",
            object_name,
            object_name
          )
        )
      }
    )

    # check sum
    ## ensure that the object loaded with this function is intended.
    ## generated by data-raw/SystemsAge_data.R or similar scripts
    if (rlang::hash(obj) != force(object_hash)) {
      stop(
        sprintf(
          "Data integrity check failed. Try re-downloading the '%s.qs2' file.",
          force(object_name)
        )
      )
    }

    return(obj)
  }
}

#' Load SystemsAge Data
#'
#' A wrapper that loads SystemsAge data from a specified or default location.
#'
#' @param path Character string specifying the file path to the .qs2 file.
#'   If `NULL`, loads from the path at [get_methylCIPHER_path()].
#' @return A list containing objects needed to calculate SystemsAge.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' SystemsAge_data <- load_SystemsAge_data()
#' SystemsAge_data <- load_SystemsAge_data("path/to/SystemsAge_data.qs2")
#' }
load_SystemsAge_data <- load_data_function("SystemsAge_data", "9a40b38aa4f95cf0da3574c87a49539c")

#' Load PCClocks Data
#'
#' A wrapper that loads PCClocks data from a specified or default location.
#'
#' @param path Character string specifying the file path to the .qs2 file.
#'   If `NULL`, loads from the path at [get_methylCIPHER_path()].
#' @return A list containing objects needed to calculate PCClocks.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' PCClocks_data <- load_PCClocks_data()
#' PCClocks_data <- load_PCClocks_data("path/to/PCClocks_data.qs2")
#' }
load_PCClocks_data <- load_data_function("PCClocks_data", "ac78e517b87e7483708baeb6b65396e2")
