# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scan_finite_unit_interval_cpp <- function(x, name = "x", require_open = FALSE) {
    invisible(.Call(`_methylCIPHERv2_scan_finite_unit_interval_cpp`, x, name, require_open))
}

gather_sample_block_cpp <- function(x, first_sample, sample_count) {
    .Call(`_methylCIPHERv2_gather_sample_block_cpp`, x, first_sample, sample_count)
}

scatter_sample_block_cpp <- function(destination, block, first_sample) {
    invisible(.Call(`_methylCIPHERv2_scatter_sample_block_cpp`, destination, block, first_sample))
}

beta_mixture_em_cpp <- function(y, initial_responsibility, nL = 3L, maxiter = 25L, tol = 1e-6, beta_maxit = 50L, beta_max_halving = 30L, beta_score_tol = 1e-10, min_shape = 1e-10, armijo = 1e-4, debug = FALSE) {
    .Call(`_methylCIPHERv2_beta_mixture_em_cpp`, y, initial_responsibility, nL, maxiter, tol, beta_maxit, beta_max_halving, beta_score_tol, min_shape, armijo, debug)
}

col_stats <- function(obj, cols = NULL, moment_sets = NULL) {
    .Call(`_methylCIPHERv2_col_stats`, obj, cols, moment_sets)
}

fill_imp_col <- function(obj, mean_vec) {
    invisible(.Call(`_methylCIPHERv2_fill_imp_col`, obj, mean_vec))
}

qnorm_target_rows_cpp <- function(obj, target) {
    .Call(`_methylCIPHERv2_qnorm_target_rows_cpp`, obj, target)
}

